const products = [
  //PRODUCTS
  {
    name: "Cat's eye",
    collection: 2021,
    id: 1,
    productCode: "CE01",
    color: "black",
    price: 96,
    image1:'/products-images/glasses 1-min.jpg',
    image2:'/products-images/glasses 1-2-min.jpg',
  },
  {
    name: "Hawk's eye",
    collection: 2021,
    id: 2,
    productCode: "HE02",
    color: "black",
    price: 90,
    image1: "/products-images/glasses 2-min.jpg",
    image2: "/products-images/glasses 2-2-min.jpg",
  },
  {
    name: "Jaguar's eye",
    collection: 2021,
    id: 3,
    productCode: "JE03",
    color: "black",
    price: 110,
    image1: "/products-images/glasses 3-min.jpg",
    image2: "/products-images/glasses 3-2-min.jpg",
  },
  {
    name: "Tiger's eye",
    collection: 2020,
    id: 4,
    productCode: "TE01",
    color: "brown",
    price: 75,
    image1: "/products-images/glasses 4-min.jpg",
    image2: "/products-images/glasses 4-2-min.jpg",
  },
  {
    name: "Panther's eye",
    collection: 2020,
    id: 5,
    productCode: "PE02",
    color: "black",
    price: 100,
    image1: "/products-images/glasses 5-min.jpg",
    image2: "/products-images/glasses 5-2-min.jpg",
  },
  {
    name: "Gold digger",
    collection: 2020,
    id: 6,
    productCode: "GD03",
    color: "gold",
    price: 110,
    image1: "/products-images/glasses 6-min.jpg",
    image2: "/products-images/glasses 6-2-min.jpg",
  },
];

export default products;
